name: Controllo Biglietti Ogni 30 Minuti

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  controlla:
    runs-on: ubuntu-latest
    steps:
    - name: Accedi al codice
      uses: actions/checkout@v4

    - name: Configura Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Installa Librerie
      run: pip install requests

    - name: Esegui il Bot
      run: python bot.py
